######################################################################
##
## Filename: cla_2test.udo
## Created on: Sun Oct 20 15:19:53 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
