######################################################################
##
## Filename: cla_32test.udo
## Created on: Mon Oct 21 16:53:16 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
