######################################################################
##
## Filename: test_32_cla.udo
## Created on: Mon Nov 04 10:54:12 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
