######################################################################
##
## Filename: test2.udo
## Created on: Mon Nov 04 11:34:04 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
