######################################################################
##
## Filename: regiletest.udo
## Created on: Mon Oct 14 21:12:38 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
