######################################################################
##
## Filename: CPU.udo
## Created on: Mon Dec 02 10:25:38 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
