######################################################################
##
## Filename: cla_1.udo
## Created on: Mon Nov 04 11:14:21 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
