######################################################################
##
## Filename: cla_32_final_test.udo
## Created on: Mon Oct 21 18:03:03 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
