######################################################################
##
## Filename: decoder_tb.udo
## Created on: Sun Oct 13 22:48:49 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
