######################################################################
##
## Filename: decoder.udo
## Created on: Sat Nov 02 9:40:45 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
