######################################################################
##
## Filename: extendtest.udo
## Created on: Mon Oct 14 23:53:47 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
