######################################################################
##
## Filename: test_uart.udo
## Created on: Tue May 06 19:05:50 中国标准时间 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
