######################################################################
##
## Filename: anti_shake_test2.udo
## Created on: Mon Dec 23 18:42:41 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
