######################################################################
##
## Filename: cpu_board_test.udo
## Created on: Mon Dec 23 19:08:24 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
