######################################################################
##
## Filename: cpu_test.udo
## Created on: Sat Nov 30 17:56:32 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
