######################################################################
##
## Filename: cpu_board_final.udo
## Created on: Sat Dec 21 12:54:43 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
