######################################################################
##
## Filename: ip_core_test.udo
## Created on: Mon Dec 16 10:32:55 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
