######################################################################
##
## Filename: ip_core.udo
## Created on: Mon Dec 16 11:00:14 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
