######################################################################
##
## Filename: barrelshitertest.udo
## Created on: Sat Oct 19 17:26:34 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
