######################################################################
##
## Filename: clk_div_test.udo
## Created on: Mon Dec 23 14:35:17 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
