######################################################################
##
## Filename: mux24a_tb.udo
## Created on: Mon Oct 14 0:14:49 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
