######################################################################
##
## Filename: alu_module.udo
## Created on: Fri Nov 08 12:33:07 中国标准时间 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
